name: Xian
version: '${version}'
main: top.zoyn.xian.Xian
api-version: 1.13
authors: [ Zoyn ]
commands:
  xian:
    aliases:
      - xiuxian
      - xunxian
      - zentia
      - xiuzhen
      - xx
    description: "修真插件主要命令"
